### ISSUE TITLE
fatal error: io_github_kasukusakura_silkcodec_NativeBridge.h: No such file or directory

### ISSUE THREAD

**Issue by suntong** [KasukuSakura/silk-codec#1]
Thanks for providing such wonderful tool first of all. 

But when I tried to build it myself, I'm getting:

```
/work/native/src/bind/NativeBridge.cpp:4:10: fatal error: io_github_kasukusakura_silkcodec_NativeBridge.h: No such file or directory
    4 | #include "io_github_kasukusakura_silkcodec_NativeBridge.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

https://github.com/KasukuSakura/silk-codec/blob/e9321202ece18be04e32207b524a25ca846f3ff0/native/src/bind/NativeBridge.cpp#L4

What steps I'm missing?

PS. This is how I'm building it myself:

```
export CROSS=linux-x64
docker run -v `pwd`:/work --env "CROSS" "dockcross/$CROSS" bash -c 'chmod +x .scripts/build.sh; /work/.scripts/build.sh'
```

Thanks

**Comment by Karlatemp** [comment]
You need to run `./gradlew compileJava` first to auto gen jni headers

**Comment by suntong** [comment]
Wow, thanks a lot for the fast response!!

Hmm.. I'm having trouble auto generating jni headers:

```
bash-4.2# cd /work
bash-4.2# find . | sort > /tmp/fl.1
bash-4.2# head !$
head /tmp/fl.1
.
./.git
./.git/HEAD
./.git/branches
./.git/config
. . .

bash-4.2# ./gradlew compileJava
Downloading https://services.gradle.org/distributions/gradle-7.1-all.zip
..............10%...............20%...............30%...............40%..............50%...............60%...............70%...............80%..............90%...............100%

Welcome to Gradle 7.1!

Here are the highlights of this release:
 - Faster incremental Java compilation
 - Easier source set configuration in the Kotlin DSL

For more details see https://docs.gradle.org/7.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 51s
2 actionable tasks: 2 up-to-date

bash-4.2# find . | sort > /tmp/fl.2

bash-4.2# diff -wU 1 /tmp/fl.1 /tmp/fl.2 | wc 
      0       0       0
```

I.e., nothing get generated under pwd, after running `./gradlew compileJava`

I saw the following prompt flashing by during it runs though:

`:ci-helper:compileJava > Resolve files of :ci-helper:compileClasspath > Generating`

**Comment by Karlatemp** [comment]
the generated headers in ./build/generated/sources/headers/java/main/

you can see the same path in CMakeList.txt and see full building steps in github ci workflow.yml

**Comment by suntong** [comment]
Ah, i finally am able to make it:

```
[100%] Linking CXX executable silk_codec
[100%] Built target silk_codec
```

Thanks!

**Comment by suntong** [comment]
BTW, I'm just curious, when and how you were able to figure it all out, the transcoding between silk and PCM?
